name: generate-terminal-gifs

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write


    #     tapes:
    #       - 'docs/vhs/install.tape'
    #       - 'docs/vhs/basic-usage.tape'
    #       - 'docs/vhs/yaml-config.tape'
    #       - 'docs/vhs/mappings-demo.tape'
    #       - 'docs/vhs/multiple-mappings.tape'
    #       - 'docs/vhs/advanced-features.tape'
    #       - 'docs/vhs/remote-content.tape'
    #       - 'docs/vhs/schema-generation.tape'

jobs:
  run-tapes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: 🚀 Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
        with:
            go-version: '1.25.1'

      - name: 🧪 Generate the gif with vhs
        if: github.actor != 'dependabot[bot]'
        run: |
          sudo apt update
          sudo apt install -y ffmpeg ttyd
          go install github.com/charmbracelet/vhs@latest

          cd docs/vhs
          vhs install.tape
          vhs basic-usage.tape
          vhs yaml-config.tape
          vhs mappings-demo.tape
          vhs multiple-mappings.tape
          vhs advanced-features.tape
          vhs remote-content.tape
          vhs schema-generation.tape
          cd ..

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: Update generated VHS GIF
          branch: repository-dispatch/update-${{ github.run_id }}
          title: Update generated VHS GIF
          body: This PR updates the generated VHS GIF files.
          base: main
          labels: automation
